document.write('<div id="topBar">');
document.write('<table><tr>');
document.write('<td>');
document.write('    <div class="menuicon" onclick="menuicon()">');
document.write('        <div class="bar1" onclick="menubar()"></div>');
document.write('        <div class="bar2" onclick="menubar()"></div>');
document.write('        <div class="bar3" onclick="menubar()"></div>');
document.write('    </div>');
document.write('    <div class="menuDropdown">');
document.write('        <div id="menuDropdownItems" class="menuDropdownList">');
document.write('            <a href="/index.html">Home</a>');
document.write('            <a href="#">Hide log messages</a>');
document.write('            <a href="#">About</a>');
document.write('        </div>');
document.write('    </div>');
document.write('</td>');
document.write('<td><a href="/index.html"><img id="companyLogo" src="custom/companyLogo.jpg" alt="Twilio"/></a></td>');
document.write('<td><h1>SMS Messaging</h1></td>');
document.write('</tr></table>');
document.write('</div>');
